# -*- coding: utf-8 -*-
"""monitor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBd9o1bl37UlASszX9iCea_eDBEtfHMs
"""

import requests

webhook = "https://open.larksuite.com/open-apis/bot/v2/hook/f7b5ae75-eb4f-4e36-9a01-557bda101139"

campaigns = [
    {"name": "New Moon Campaign", "roas": 4.3, "spend": 25000},
    {"name": "Pampers Campaign", "roas": 12.1, "spend": 48000},
    {"name": "Mirai Campaign", "roas": 3.9, "spend": 32000}
]

threshold = 5

for campaign in campaigns:
    if campaign["roas"] < threshold:

        message = {
            "msg_type": "text",
            "content": {
                "text": f"⚠️ ROAS ALERT\nCampaign: {campaign['name']}\nROAS: {campaign['roas']}"
            }
        }

        requests.post(webhook, json=message)