name: Ads Monitoring

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requests
        run: pip install requests

      - name: Run monitoring script
        run: python monitor_py.py
        env:
          TIKTOK_ACCESS_TOKEN: ${{ secrets.TIKTOK_ACCESS_TOKEN }}
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
          LARK_WEBHOOK_GROUP: ${{ secrets.LARK_WEBHOOK_GROUP }}
